# Generated by Django 4.2.6 on 2023-11-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefono', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='fecha_creacion',
            field=models.CharField(max_length=30),
        ),
    ]
