# Generated by Django 4.2.6 on 2023-11-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefono', '0003_alter_telefono_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='telefonos/'),
        ),
    ]
