# Generated by Django 4.2.6 on 2023-11-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefono', '0004_telefono_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='FotoTelefono'),
        ),
    ]
