# Generated by Django 4.2.6 on 2023-11-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auricular', '0002_alter_auricular_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auricular',
            name='fecha_creacion',
            field=models.CharField(max_length=30),
        ),
    ]
