# Generated by Django 4.2.6 on 2023-11-18 17:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auricular', '0003_alter_auricular_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='auricular',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='FotoAuricular'),
        ),
        migrations.AlterField(
            model_name='auricular',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='auricular',
            name='fecha_creacion',
            field=models.DateField(),
        ),
    ]
