# Generated by Django 4.2.6 on 2023-11-18 16:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reloj',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='FotoTelefono'),
        ),
        migrations.AlterField(
            model_name='reloj',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='reloj',
            name='fecha_creacion',
            field=models.DateField(),
        ),
    ]
