# Generated by Django 4.2.6 on 2023-11-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj', '0002_reloj_foto_alter_reloj_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reloj',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='FotoReloj'),
        ),
    ]
