# Generated by Django 4.2.6 on 2023-11-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_datosextra_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='biografia',
            field=models.CharField(max_length=300),
        ),
    ]
