# Generated by Django 4.2.6 on 2023-11-18 03:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_datosextra_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='biografia',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
